name: pos_system
description: "POS System (Flutter + PocketBase)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # STATE MANAGEMENT
  provider: ^6.1.2

  # POCKETBASE

  pocketbase: ^0.24.0
  http: ^1.6.0

  cached_network_image: ^3.3.1
  uuid: ^4.5.1
  image: ^4.3.0
  fl_chart: ^0.70.0
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.13.4
  unified_esc_pos_printer: ^3.2.0
  shared_preferences: ^2.5.3  
  url_launcher: ^6.3.1
  font_awesome_flutter: ^11.0.0
  # keyboard 
  hotkey_manager: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
