class PakistanMobileCatalog {
  static const Map<String, List<String>> brands = {
    'Apple': [
      'iPhone 16 Pro Max',
      'iPhone 16 Pro',
      'iPhone 16 Plus',
      'iPhone 16',
      'iPhone 15 Pro Max',
      'iPhone 15 Pro',
      'iPhone 15 Plus',
      'iPhone 15',
      'iPhone 14 Pro Max',
      'iPhone 14 Pro',
      'iPhone 14 Plus',
      'iPhone 14',
      'iPhone 13 Pro Max',
      'iPhone 13 Pro',
      'iPhone 13',
      'iPhone 13 Mini',
      'iPhone 12 Pro Max',
      'iPhone 12 Pro',
      'iPhone 12',
      'iPhone 12 Mini',
      'iPhone 11 Pro Max',
      'iPhone 11 Pro',
      'iPhone 11',
      'iPhone XS Max',
      'iPhone XS',
      'iPhone XR',
      'iPhone X',
      'iPhone 8 Plus',
      'iPhone 8',
      'iPhone 7 Plus',
      'iPhone 7',
      'iPhone 6s Plus',
      'iPhone 6s',
      'iPhone SE',
    ],
    'Samsung': [
      'Galaxy S25 Ultra',
      'Galaxy S25+',
      'Galaxy S25',
      'Galaxy S24 Ultra',
      'Galaxy S24+',
      'Galaxy S24',
      'Galaxy S23 Ultra',
      'Galaxy S23+',
      'Galaxy S23',
      'Galaxy S22 Ultra',
      'Galaxy S22+',
      'Galaxy S22',
      'Galaxy S21 Ultra',
      'Galaxy S21 FE',
      'Galaxy Note 20 Ultra',
      'Galaxy Note 20',
      'Galaxy Z Fold 6',
      'Galaxy Z Flip 6',
      'Galaxy A56',
      'Galaxy A55',
      'Galaxy A36',
      'Galaxy A35',
      'Galaxy A26',
      'Galaxy A25',
      'Galaxy A16',
      'Galaxy A15',
      'Galaxy A14',
      'Galaxy A13',
      'Galaxy A12',
      'Galaxy A06',
      'Galaxy A05s',
      'Galaxy A05',
      'Galaxy A04s',
      'Galaxy A04',
      'Galaxy M55',
      'Galaxy M35',
      'Galaxy M15',
    ],
    'Infinix': [
      'Note 50 Pro+',
      'Note 50 Pro',
      'Note 50',
      'Note 40 Pro+',
      'Note 40 Pro',
      'Note 40',
      'Note 30 Pro',
      'Note 30',
      'Zero 40',
      'Zero 30',
      'GT 20 Pro',
      'GT 10 Pro',
      'Hot 50 Pro+',
      'Hot 50 Pro',
      'Hot 50',
      'Hot 50i',
      'Hot 40 Pro',
      'Hot 40',
      'Hot 40i',
      'Hot 30',
      'Hot 30i',
      'Smart 9 HD',
      'Smart 9',
      'Smart 8 Plus',
      'Smart 8',
      'Smart 7',
    ],
    'Tecno': [
      'Camon 40 Premier',
      'Camon 40 Pro',
      'Camon 40',
      'Camon 30 Premier',
      'Camon 30 Pro',
      'Camon 30',
      'Camon 20 Premier',
      'Camon 20 Pro',
      'Camon 20',
      'Phantom V Fold 2',
      'Phantom V Flip 2',
      'Pova 6 Pro',
      'Pova 6',
      'Pova 5 Pro',
      'Pova 5',
      'Spark 30 Pro',
      'Spark 30',
      'Spark 30C',
      'Spark 20 Pro+',
      'Spark 20 Pro',
      'Spark 20',
      'Spark 20C',
      'Spark 10 Pro',
      'Spark 10',
      'Pop 9',
      'Pop 8',
      'Pop 7',
    ],
    'Oppo': [
      'Find X8 Pro',
      'Find X8',
      'Reno 13 Pro',
      'Reno 13',
      'Reno 12 Pro',
      'Reno 12',
      'Reno 11 Pro',
      'Reno 11',
      'Reno 10 Pro',
      'Reno 10',
      'Reno 8 Pro',
      'Reno 8',
      'F27 Pro',
      'F25 Pro',
      'F21 Pro',
      'A3 Pro',
      'A60',
      'A59',
      'A58',
      'A57',
      'A38',
      'A18',
      'A17',
      'A16',
      'A15',
      'A12',
      'A5s',
    ],
    'Vivo': [
      'X200 Pro',
      'X200',
      'X100 Pro',
      'X100',
      'V50',
      'V40 Pro',
      'V40',
      'V30 Pro',
      'V30',
      'V29',
      'V27',
      'V25',
      'V23',
      'Y200',
      'Y100',
      'Y38',
      'Y28',
      'Y27',
      'Y22',
      'Y21',
      'Y20',
      'Y19s',
      'Y18',
      'Y17s',
      'Y16',
      'Y15s',
      'Y12',
      'Y11',
    ],
    'Xiaomi / Redmi': [
      'Xiaomi 15 Ultra',
      'Xiaomi 15',
      'Xiaomi 14 Ultra',
      'Xiaomi 14',
      'Xiaomi 13T Pro',
      'Xiaomi 13T',
      'Redmi Note 14 Pro+',
      'Redmi Note 14 Pro',
      'Redmi Note 14',
      'Redmi Note 13 Pro+',
      'Redmi Note 13 Pro',
      'Redmi Note 13',
      'Redmi Note 12 Pro',
      'Redmi Note 12',
      'Redmi Note 11 Pro',
      'Redmi Note 11',
      'Redmi 14C',
      'Redmi 13C',
      'Redmi 12',
      'Redmi 12C',
      'Redmi 10C',
      'Redmi 10',
      'Redmi A4',
      'Redmi A3',
      'Redmi A2+',
      'Redmi A2',
      'Redmi A1+',
      'Poco F6 Pro',
      'Poco F6',
      'Poco X6 Pro',
      'Poco X6',
      'Poco M6 Pro',
      'Poco M6',
      'Poco C75',
      'Poco C65',
    ],
    'Realme': [
      'GT 7 Pro',
      'GT 6',
      'GT Neo 6',
      '13 Pro+',
      '13 Pro',
      '13',
      '12 Pro+',
      '12 Pro',
      '12',
      '11 Pro+',
      '11 Pro',
      '11',
      'C75',
      'C67',
      'C65',
      'C63',
      'C61',
      'C55',
      'C53',
      'C51',
      'C35',
      'C33',
      'C25',
      'C21Y',
      'Note 60',
      'Note 50',
    ],
    'OnePlus': [
      'OnePlus 13',
      'OnePlus 13R',
      'OnePlus 12',
      'OnePlus 12R',
      'OnePlus 11',
      'OnePlus 10 Pro',
      'OnePlus 10T',
      'OnePlus 9 Pro',
      'OnePlus 9',
      'OnePlus 8 Pro',
      'OnePlus 8T',
      'OnePlus Nord 4',
      'OnePlus Nord 3',
      'OnePlus Nord CE 4',
      'OnePlus Nord CE 3',
      'OnePlus Nord N30',
    ],
    'Google Pixel': [
      'Pixel 9 Pro Fold',
      'Pixel 9 Pro XL',
      'Pixel 9 Pro',
      'Pixel 9',
      'Pixel 8 Pro',
      'Pixel 8',
      'Pixel 8a',
      'Pixel 7 Pro',
      'Pixel 7',
      'Pixel 7a',
      'Pixel 6 Pro',
      'Pixel 6',
      'Pixel 6a',
      'Pixel 5',
      'Pixel 4 XL',
      'Pixel 4',
    ],
    'Honor': [
      'Magic 7 Pro',
      'Magic 6 Pro',
      'Magic V3',
      'Honor 200 Pro',
      'Honor 200',
      'Honor 100',
      'Honor 90',
      'Honor 70',
      'Honor X9c',
      'Honor X9b',
      'Honor X8c',
      'Honor X8b',
      'Honor X7c',
      'Honor X7b',
      'Honor X6b',
      'Honor X5b',
    ],
    'Huawei': [
      'Pura 70 Ultra',
      'Pura 70 Pro',
      'Pura 70',
      'Mate 60 Pro',
      'Mate 50 Pro',
      'P50 Pro',
      'P40 Pro',
      'Nova 13 Pro',
      'Nova 13',
      'Nova 12',
      'Nova 11',
      'Nova 10',
      'Nova 9',
      'Y9 Prime',
      'Y9s',
      'Y7a',
      'Y6p',
      'Y5p',
    ],
    'Itel': [
      'S25 Ultra',
      'S25',
      'S24',
      'S23+',
      'S23',
      'A80',
      'A70',
      'A60s',
      'A60',
      'P65',
      'P55+',
      'P55',
      'P40+',
      'P40',
      'Vision 3 Plus',
    ],
    'Sparx': [
      'Edge 20 Pro',
      'Edge 20',
      'Neo 8 Pro',
      'Neo 8',
      'Neo 7 Ultra',
      'Neo 7 Plus',
      'Neo 7',
      'Neo 6 Plus',
      'Neo 6',
      'Neo 5 Plus',
      'Neo 5',
      'S9',
      'S7',
    ],
    'Dcode': [
      'Bold 3 Pro',
      'Bold 3',
      'Bold 2 Pro',
      'Bold 2',
      'Bold',
      'Cygnal 3 Pro',
      'Cygnal 3',
      'Cygnal 2 Pro',
      'Cygnal 2',
      'Cygnal',
    ],
    'QMobile': [
      'QSmart Blaze',
      'QSmart LT950',
      'QSmart LT900',
      'QSmart Hot Pro 2',
      'QSmart Hot Pro',
      'Noir Z14',
      'Noir Z12 Pro',
      'Noir Z10',
      'Noir S6 Plus',
      'Noir S6',
      'Noir i8i',
    ],
    'Nokia': [
      'Nokia G42',
      'Nokia G21',
      'Nokia G20',
      'Nokia G10',
      'Nokia C32',
      'Nokia C31',
      'Nokia C22',
      'Nokia C21 Plus',
      'Nokia C20',
      'Nokia 8.3',
      'Nokia 7.2',
      'Nokia 6.2',
      'Nokia 5.4',
      'Nokia 3.4',
      'Nokia 2.4',
    ],
    'Motorola': [
      'Razr 50 Ultra',
      'Razr 50',
      'Edge 50 Ultra',
      'Edge 50 Pro',
      'Edge 50 Fusion',
      'Edge 40 Pro',
      'Edge 40',
      'Moto G85',
      'Moto G75',
      'Moto G64',
      'Moto G54',
      'Moto G24',
      'Moto G14',
      'Moto E14',
      'Moto E13',
    ],
    'ZTE': [
      'Nubia Z70 Ultra',
      'Nubia Z60 Ultra',
      'Nubia RedMagic 10 Pro',
      'Nubia RedMagic 9 Pro',
      'ZTE Blade V70',
      'ZTE Blade V60',
      'ZTE Blade A75',
      'ZTE Blade A55',
      'ZTE Blade A35',
    ],
    'Nothing': [
      'Nothing Phone (3a) Pro',
      'Nothing Phone (3a)',
      'Nothing Phone (2a) Plus',
      'Nothing Phone (2a)',
      'Nothing Phone (2)',
      'Nothing Phone (1)',
      'CMF Phone 1',
    ],
    'Sony': [
      'Xperia 1 VI',
      'Xperia 1 V',
      'Xperia 5 V',
      'Xperia 10 VI',
      'Xperia 10 V',
      'Xperia 1 IV',
      'Xperia 5 IV',
      'Xperia XZ3',
      'Xperia XZ2',
    ],
    'LG': [
      'LG Wing',
      'LG Velvet',
      'LG V60 ThinQ',
      'LG V50 ThinQ',
      'LG G8 ThinQ',
      'LG G7 ThinQ',
      'LG K92',
      'LG K52',
      'LG K42',
    ],
    'Other': ['Other / Custom model'],
  };

  static List<String> get brandNames => brands.keys.toList();

  static List<String> modelsFor(String brand) =>
      List<String>.from(brands[brand] ?? const ['Other / Custom model']);
}
